# Generated by Django 5.2.8 on 2025-11-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arff_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arfffile',
            name='file',
            field=models.FileField(upload_to='arffs/'),
        ),
    ]
